server:
  port: 8080
spring:
  application:
    name: "agencia-viajes"
  devtools:
    add-properties: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  profiles:
    include: null
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=agencia_viajes"
    username: "postgres"
    password: "root"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      hibernate:
        format_sql: true
    show-sql: true
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
app:
  async:
    app:
      withDLQRetry: false
      maxRetries: -1
      retryDelay: 1000